### ISSUE TITLE
livescript 1.3+ eats command line arguments

### ISSUE THREAD

**Issue by bramp** [yhsiang/irccloud-cli#14]
Previously you could type
    bin/ic -P . -v
however, livescript now thinks the -P is for it, so it displays a error message. The correct new command line is:
    bin/ic -- -P . -v

There is a bug against livescript https://github.com/gkz/LiveScript/issues/610 to resolve this. Until then maybe the documentation should be updated?

**Comment by yhsiang** [comment]
sure, I will take this :)

**Comment by yhsiang** [comment]
Rewrite with ES2015. So close this issue.
